---
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  CodeStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration: 
        Status: Enabled
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /
      Policies:
        - PolicyName: AllowCodeStorageBucketAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource: !Sub arn:aws:s3:::${CodeStorageBucket}/*

Outputs:
  CodeStorageBucket:
    Description: Default bucket for Swiftda-managed functions
    Value: !Ref CodeStorageBucket
    Export:
      Name: SwiftdaCodeStorageBucket
  ExecutionRoleArn:
    Description: ARN of default Lambda execution role for Swiftda-managed functions
    Value: !GetAtt ExecutionRole.Arn
    Export:
      Name: SwiftdaExecutionRoleArn
